name: Create Azure AKS With Terraform
on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
jobs: 
  AKS-Cluster-Deployment:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        
      - uses: hashicorp/setup-terraform@v3
        with:
            terraform_version: "1.1.7"
        
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
      - name: azure cli
        uses: azure/CLI@v1
        with:
           azcliversion: latest
           inlineScript: |
             az account show
  

      - name: Terraform Initiliza
        run: terraform init
      
      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
             

      - name: Terraform Output
        run: terraform output
